steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "-t",
        "gcr.io/djangocutter-341220/djangocutter:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/djangocutter-341220/djangocutter:latest"]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "djangocutter",
        "--image",
        "gcr.io/djangocutter-341220/djangocutter:latest",
        "--region",
        "europe-west4",
      ]

substitutions:
  _INSTANCE_NAME: django-cutter
  _SERVICE_NAME: djangocutter
  _SECRET_SETTINGS_NAME: config.settings.production

images:
  - gcr.io/djangocutter-341220/djangocutter:latest
